### ISSUE TITLE
一个报错

### ISSUE THREAD

**Issue by foralliance** [chengyangfu/caffe#20]
执行python examples/ssd/ssd_pascal_resnet_321.py时，报错：

Traceback (most recent call last):
  File "examples/ssd/ssd_pascal_resnet_321.py", line 431, in <module>
    inter_layer_depth=inter_layer_depth)
  File "/home/jmx/SSD/caffe/python/caffe/model_libs.py", line 798, in CreateMultiBoxHead
    assert num_classes, "must provide num_classes"
AssertionError: must provide num_classes

我的DSSD是放在/home/jmx/DSSD/caffe下的，也一直是在该文件下进行编译和操作，为什么会报另一个路径的/home/jmx/SSD/caffe错误？？
麻烦了！

**Comment by foralliance** [comment]
问题已解决，谢谢
